export default {
  icon: {
    $type: 'icon',

    main:              { $value: '"\\E000"' },
    nav:               { $value: '"\\E001"' },
    search:            { $value: '"\\E002"' },
    profile:           { $value: '"\\E003"' },
    play:              { $value: '"\\E004"' },
    publication:       { $value: '"\\E005"' },
    close:             { $value: '"\\E006"' },
    clear:             { $value: '"\\E007"' },
    arrowRight:        { $value: '"\\E008"' },
    arrowDown:         { $value: '"\\E009"' },
    arrowUp:           { $value: '"\\E00A"' },
    slideLeftSmall:    { $value: '"\\E00B"' },
    slideRightSmall:   { $value: '"\\E00C"' },
    slideLeftMiddle:   { $value: '"\\E00D"' },
    slideRightMiddle:  { $value: '"\\E00E"' },
    slideLeftBig:      { $value: '"\\E00F"' },

    slideRightBig:     { $value: '"\\E010"' },
    maximize:          { $value: '"\\E011"' },
    minimize:          { $value: '"\\E012"' },
    star:              { $value: '"\\E013"' },
    today:             { $value: '"\\E014"' },
    liveNews:          { $value: '"\\E015"' },
    leadingNews:       { $value: '"\\E016"' },
    show:              { $value: '"\\E017"' },
    hide:              { $value: '"\\E018"' },
    camera:            { $value: '"\\E019"' },
    check:             { $value: '"\\E01A"' },
    dropdownArrow:     { $value: '"\\E01B"' },
    threeDots:         { $value: '"\\E01C"' },
    thumbsUp:          { $value: '"\\E01D"' },
    thumbsDown:        { $value: '"\\E01E"' },
    ban:               { $value: '"\\E01F"' },
  
    social:            { $value: '"\\E100"' },
    facebook:          { $value: '"\\E101"' },
    x:                 { $value: '"\\E102"' },
    viber:             { $value: '"\\E103"' },
    email:             { $value: '"\\E104"' },
    rss:               { $value: '"\\E105"' },
    telegram:          { $value: '"\\E106"' },
    linkedin:          { $value: '"\\E107"' },
    link:              { $value: '"\\E108"' },
    print:             { $value: '"\\E109"' },
    heart:             { $value: '"\\E10A"' },
    googleMark:        { $value: '"\\E10B"' },
    facebookMark:      { $value: '"\\E10C"' },
    appleMark:         { $value: '"\\E10D"' },
    era:               { $value: '"\\E10E"' },
    home:              { $value: '"\\E10F"' },

    heartFilled:       { $value: '"\\E020"' },
    thumbsUpFilled:    { $value: '"\\E021"' },
    thumbsDownFilled:  { $value: '"\\E022"' },
    readings:          { $value: '"\\E023"' },
    comments:          { $value: '"\\E024"' },
    thumbsUp2:         { $value: '"\\E025"' },
    thumbsDown2:       { $value: '"\\E026"' },
    thumbsUp2Filled:   { $value: '"\\E027"' },
    thumbsDown2Filled: { $value: '"\\E028"' },
    bookmark:          { $value: '"\\E029"' },
    bookmarkFilled:    { $value: '"\\E02A"' },

    plus:              { $value: '"\\E110"' },
    weather:           { $value: '"\\E200"' },

    astrology:         { $value: '"\\E300"' },
    capricorn:         { $value: '"\\E301"' },
    aquarius:          { $value: '"\\E302"' },
    pisces:            { $value: '"\\E303"' },
    aries:             { $value: '"\\E304"' },
    taurus:            { $value: '"\\E305"' },
    gemini:            { $value: '"\\E306"' },
    cancer:            { $value: '"\\E307"' },
    leo:               { $value: '"\\E308"' },
    virgo:             { $value: '"\\E309"' },
    libra:             { $value: '"\\E30A"' },
    scorpio:           { $value: '"\\E30B"' },
    sagittarius:       { $value: '"\\E30C"' }
  }
};
